import os
import re
from typing import TYPE_CHECKING
from dotenv import load_dotenv

import streamlit as st
import boto3

from logics.rag_logics_en import call_rag

if TYPE_CHECKING:
    from mypy_boto3_bedrock_agent_runtime.client import AgentsforBedrockRuntimeClient
    from mypy_boto3_bedrock_runtime.client import BedrockRuntimeClient


load_dotenv(".env", verbose=True)

KNOWLEDGE_BASE_ID = os.environ.get("KNOWLEDGE_BASE_ID")
MODEL_ID = "anthropic.claude-3-haiku-20240307-v1:0"
REGION = "ap-northeast-1"

agents_for_bedrock_runtime: "AgentsforBedrockRuntimeClient" = boto3.client(
    "bedrock-agent-runtime", region_name=REGION)
bedrock_runtime: "BedrockRuntimeClient" = boto3.client(
    service_name="bedrock-runtime",
    region_name=REGION
)


def split_answer_and_thinking(llm_output: str) -> dict:
    """The output generated by the LLM is wrapped with <thinking></thinking> 
    and <answer></answer> tags, so this function separates them.
    """
    result = {"answer": "", "thinking": ""}
    thinking_match = re.search(r'<thinking>(.*?)</thinking>', llm_output, re.DOTALL)
    if thinking_match:
        result["thinking"] = thinking_match.group(1).strip()

    # Extract the content within the <answer> tag
    answer_match = re.search(r'<answer>(.*?)</answer>', llm_output, re.DOTALL)
    if answer_match:
        result["answer"] = answer_match.group(1).strip()

    return result


def main():
    # Streamlit application
    st.title("Bedrock Chat App")
    st.sidebar.title("LLM's Thought Process Output")
    thinking_display = st.sidebar.empty()
    st.sidebar.title("Search Results")
    context_display = st.sidebar.empty()

    # Initialize session state
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Display chat history
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # User input
    if question := st.chat_input("Enter your question here"):
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)
        response, context = call_rag(
            question,
            KNOWLEDGE_BASE_ID,
            agents_for_bedrock_runtime,
            bedrock_runtime,
            MODEL_ID
        )
        splitted_output = split_answer_and_thinking(response)
        # Display the LLM's reasoning process in the sidebar
        with thinking_display.container():
            st.markdown(splitted_output["thinking"])
        # Display search results in the sidebar
        with context_display.container():
            st.json(context)

        # Display the final answer
        st.session_state.messages.append({"role": "assistant", "content": splitted_output["answer"]})
        with st.chat_message("assistant"):
            st.markdown(splitted_output["answer"])


if __name__ == "__main__":
    main()