from typing import TYPE_CHECKING
import json


if TYPE_CHECKING:
    from mypy_boto3_bedrock_agent_runtime.client import AgentsforBedrockRuntimeClient
    from mypy_boto3_bedrock_runtime.client import BedrockRuntimeClient
    from mypy_boto3_bedrock_runtime.type_defs import ToolTypeDef
    from mypy_boto3_bedrock_agent_runtime.type_defs import (
        KnowledgeBaseRetrievalResultTypeDef,
    )


PROMPT_TEMPLATE = """
<background>
You are an AI assistant that answers questions from tourists about sightseeing information in Tokyo.  
Your role is to help visitors enjoy their stay in Tokyo.  
Always respond politely and kindly to tourists.
</background>

The section enclosed in <context></context> below contains a list of search results that are considered relevant to the user's question.  
Please read it carefully.
<context>
{context}
</context>

Please answer the user's question sincerely based on the information provided within <context></context>.  
When responding, follow the rules defined in <rules></rules>.
<rules>
- If the answer to a factual question is not written in <context></context>, please honestly respond with "I don’t know."  
  Pay extra attention to items not explicitly marked as "recommended."
- Do not include any mention of <context></context> in your final <answer></answer>.
- Always remember that the person you are talking to is a tourist.
</rules>

<rules_recommendation>
- If the user’s question includes the word "recommendation" (おすすめ) and the answer is not found in <context></context>,  
  please provide your own recommendation.  
  In such a case, append the following note at the end of your answer:  
  "＊This answer is generated by AI without relying on search results, so it may differ from actual facts."  
  (Apply this only when the question includes “recommendation.”)
- Do not include any mention of <context></context> in your <answer></answer>.
- Always remember that you are speaking to a tourist.
</rules_recommendation>

When constructing your answer, follow the steps defined in <steps></steps>.
<steps>
1. First, classify the question as one that includes "recommendation" or not.
2. If it includes "recommendation," follow the rules in <rules_recommendation></rules_recommendation> and answer accordingly.
3. Otherwise, follow the rules in <rules></rules> to respond to the tourist.
</steps>

The section enclosed in <question></question> below contains the user’s question.
<question>
{question}
</question>

Before giving your final answer, record your reasoning process within the <thinking></thinking> tag,  
and then write your final response inside the <answer></answer> tag.
"""

# Change: Added a prompt for generating a search query
QUERY_GENERATE_TEMPLATE = """
You are an expert in generating search queries related to Tokyo sightseeing information.  
Your task is to analyze the user's question and generate an optimal search query.  
The goal is to retrieve data relevant to the user's question.  
The search combines both semantic and keyword-based methods.

When creating the query, follow the rules defined in <rules></rules>.
<rules>
1. The query should be concise and specific.
2. Include important keywords related to Tokyo tourism.
3. Prefer concrete nouns and proper nouns over general expressions.
4. Accurately reflect the intent of the user’s question.
5. Omit unnecessary conjunctions and particles.
6. Assume the query will be used in a search engine; avoid natural-language question forms—use keyword-based expressions.
7. Remove vague terms such as "recommendation" (おすすめ).
</rules>

Below, <question></question> contains the user’s question:
<question>
{question}
</question>

Please describe your reasoning process inside the <thinking></thinking> tag.  
Use the "query" tool to output the final search query you have generated.
"""

tool_list: list["ToolTypeDef"] = [
    {
        "toolSpec": {
            "name": "query",
            "description": "Function that performs a search using the generated search query",
            "inputSchema": {
                "json": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "Search query"}
                    },
                    "required": ["query"],
                }
            },
        }
    }
]


def invoke_llm(
    prompt: str,
    model_id: str,
    bedrock_runtime_client: "BedrockRuntimeClient",
    tools: list["ToolTypeDef"] = [],  # Change: added tools parameter
) -> str:
    if tools:
        response = bedrock_runtime_client.converse(
            modelId=model_id,
            messages=[
                {
                    "role": "user",
                    "content": [{"text": prompt}],
                }
            ],
            toolConfig={"tools": tools},
            inferenceConfig={"temperature": 0.0},
        )
    else:
        response = bedrock_runtime_client.converse(
            modelId=model_id,
            messages=[
                {
                    "role": "user",
                    "content": [{"text": prompt}],
                }
            ],
            inferenceConfig={"temperature": 0.0},
        )
    content_blocks = response["output"]["message"]["content"]
    for content_block in content_blocks:
        # If the LLM used a tool (tool use) and invoked query generation, return that result
        if "toolUse" in content_block:
            tool_use_block = content_block["toolUse"]
            tool_name = tool_use_block["name"]
            tool_input = tool_use_block["input"]
            assert tool_name == "query", "LLM requested unexpected tool %s" % tool_name
            print("Generated query: ", tool_input["query"])
            return tool_input["query"]
        elif "text" in content_block:
            return content_block["text"]
    raise ValueError("Unexpected response from LLM. %s", response)


# Function to retrieve context
def retrieve_context(
    query: str, knowledge_base_id: str, client_runtime: "AgentsforBedrockRuntimeClient"
) -> list["KnowledgeBaseRetrievalResultTypeDef"]:
    response = client_runtime.retrieve(
        knowledgeBaseId=knowledge_base_id,
        retrievalConfiguration={
            "vectorSearchConfiguration": {
                "overrideSearchType": "SEMANTIC",
                "numberOfResults": 10,  # Change: increased number of search results
            }
        },
        retrievalQuery={"text": query},
    )
    return response["retrievalResults"]


def call_rag(
    question: str,
    knowledge_base_id: str,
    client_runtime: "AgentsforBedrockRuntimeClient",
    bedrock_runtime_client: "BedrockRuntimeClient",
    model_id="anthropic.claude-3-sonnet-20240229-v1:0",
) -> tuple[str, list["KnowledgeBaseRetrievalResultTypeDef"]]:
    """Call the RAG system"""
    # Change: added query generation flow
    query_generate_prompt = QUERY_GENERATE_TEMPLATE.format(question=question)
    query = invoke_llm(
        query_generate_prompt, model_id, bedrock_runtime_client, tool_list
    )
    # Change: use the generated query for the retrieval step
    context = retrieve_context(query, knowledge_base_id, client_runtime)
    prompt = PROMPT_TEMPLATE.format(
        context=json.dumps(context, ensure_ascii=False), question=question
    )
    llm_response = invoke_llm(prompt, model_id, bedrock_runtime_client)
    return (llm_response, context)